# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 411))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bucketTree = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        self.bucketTree.setObjectName("bucketTree")
        self.gridLayout.addWidget(self.bucketTree, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 4, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelProject = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelProject.setObjectName("labelProject")
        self.gridLayout_2.addWidget(self.labelProject, 6, 1, 1, 1)
        self.labelBucket = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelBucket.setObjectName("labelBucket")
        self.gridLayout_2.addWidget(self.labelBucket, 6, 0, 1, 1)
        self.detailBucket = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.detailBucket.setObjectName("detailBucket")
        self.gridLayout_2.addWidget(self.detailBucket, 7, 0, 1, 1)
        self.detailProject = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.detailProject.setObjectName("detailProject")
        self.gridLayout_2.addWidget(self.detailProject, 7, 1, 1, 1)
        self.labelName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelName.setObjectName("labelName")
        self.gridLayout_2.addWidget(self.labelName, 0, 0, 1, 1)
        self.detailNextAction = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.detailNextAction.setObjectName("detailNextAction")
        self.gridLayout_2.addWidget(self.detailNextAction, 9, 0, 1, 2)
        self.detailName = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.detailName.setObjectName("detailName")
        self.gridLayout_2.addWidget(self.detailName, 1, 0, 1, 2)
        self.labelNextAction = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelNextAction.setObjectName("labelNextAction")
        self.gridLayout_2.addWidget(self.labelNextAction, 8, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 3, 1, 1)
        self.projectTree = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        self.projectTree.setObjectName("projectTree")
        self.gridLayout.addWidget(self.projectTree, 1, 1, 1, 1)
        self.taskList = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        self.taskList.setObjectName("taskList")
        self.gridLayout.addWidget(self.taskList, 0, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bucketTree.headerItem().setText(0, _translate("MainWindow", "Buckets"))
        self.label_5.setText(_translate("MainWindow", "Comments"))
        self.labelProject.setText(_translate("MainWindow", "Project"))
        self.labelBucket.setText(_translate("MainWindow", "Bucket"))
        self.labelName.setText(_translate("MainWindow", "Name"))
        self.labelNextAction.setText(_translate("MainWindow", "Next action"))
        self.projectTree.headerItem().setText(0, _translate("MainWindow", "Projects"))
        self.taskList.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.taskList.headerItem().setText(1, _translate("MainWindow", "ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
